In [4]:
l=[10,10,"Messi",['Ronaldo',7],(11,'Neymar')]
print(l)

[10, 10, 'Messi', ['Ronaldo', 7], (11, 'Neymar')]


In [5]:
l=[1,2,3]
if 1 in l:
    print("Exist")
else:
    print("Does not exist")

Exist


In [6]:
l=[1,2,3,4,5]
print(len(l))

5


In [7]:
l=[]
for i in range(1,6):
    l.append(i**2)
print(l)

[1, 4, 9, 16, 25]


In [9]:
l=[2,1,5,3,7]
l.reverse()
print(l)

[7, 3, 5, 1, 2]


In [13]:
l=[4,2,5,7,1,3,6]
l.sort(reverse=True)
print(l)

[7, 6, 5, 4, 3, 2, 1]


In [19]:
l1=[1,2,3]
l2=[1,2,3]

def cmp(l1,l2):
    if l1==l2:
        return True
#     elif(l1.sort()==l2.sort()):
#             return True
    else:
        return False

print(cmp(l1,l2))

True


In [1]:
l=[1,2,3]
l.remove(1)
print(l)

l=[1,2,2,2,4,3]
l.pop(2)
print(l)

l=[1,2,2,3]
l.clear()
print(l)


[2, 3]
[1, 2, 2, 4, 3]
[]


In [29]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
farr = np.asfarray(arr)
print(farr)

[1. 2. 3. 4. 5.]


In [31]:
import numpy as np

l=[1,2,3,4,5]
t=(1,2,3,4,5)

l_arr=np.array(l)
t_arr=np.array(t)
print(l_arr)
print(t_arr)

[1 2 3 4 5]
[1 2 3 4 5]


In [32]:
import numpy as np

l=[1,2,3,4,5]
t=(1,2,3,4,5)

l_arr=np.asarray(l)
t_arr=np.asarray(t)
print(l_arr)
print(t_arr)

[1 2 3 4 5]
[1 2 3 4 5]


In [34]:
import numpy as np

arr=np.arange(2,6).reshape(4)
print(arr)

[2 3 4 5]


In [35]:
import numpy as np

arr=np.arange(2,10).reshape(2,4)
print(arr)

[[2 3 4 5]
 [6 7 8 9]]


In [36]:
import numpy as np

arr=np.arange(24).reshape(4,3,2)
print(arr)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
